# Site settings
title: marilloW
header-img: img/home-bg.jpg
email: qs_soul@163.com
# copyright_name: Your/Project/Corporate Name
description: "I'm so cool!"
baseurl: "/qinbushou.github.io"
# url: "http://yourdomain.com"
# twitter_username: SBootstrap
github_username:  marillo
# facebook_username:  StartBootstrap
email_username:  qs_soul@163.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
